#This script compiles files for individual AusPlots that contain vegetation point intercept hit data into a single object/file and subsequently generates a species~sites occurrence matrix with percent cover scores as values. 
#
#Authors:
#Greg Guerin

library(R.utils)
library(plyr)
library(simba)

file_list <- Sys.glob("./extractedData/veg/vegPI*.csv") #call a list of files with same prefix, where 'extractedData' folder was generated by 'read_ausplots_data.R'


trim.trailing <- function (x) sub("\\s+$", "", x) #function that strips trailing white spaces from entries in d.f.

#function to open files from a list, and append the data to a single output file
extract_hits <- function(file_list) {
	working_file <- read.csv(file=file_list[1])	
	document <- as.data.frame(matrix(nrow=1, ncol=ncol(working_file))) 
	colnames(document) <- colnames(working_file)
	for (i in 1:length(file_list)) {
	working_file <- try(read.csv(file=file_list[i]))
	if(class(working_file)=="try-error") {
		working_file <- NULL
	}
	if(class(working_file)=="data.frame") {
		document <- rbind(document, working_file)
	}
	
	message("Dataset added")
	message(i)
	}
document <- document[-1,]
write.csv(document, file="PI_compiled.txt")
}

extract_hits(file_list) #run the function - generates a file with PI hits as rows, identified by site name, species and transect number; NO  further clean has been performed, just compiling rows of the raw data.

hits <- read.csv(file="PI_compiled.txt") #read file back into R

#...  needs further clearing up as follows
hits$herbarium_determination <- trim.trailing(hits$herbarium_determination) #clear white spaces that interfere with recognising duplicate entries as same species
hits$herbarium_determination <- tolower(hits$herbarium_determination)
hits$herbarium_determination <- capitalize(hits$herbarium_determination)

#manually correct an odd transect identifier:
delete <- grep("W5-.E", hits$transect)
hits$transect[delete] <- "W5-E5" 
hits$transect <- as.factor(as.character(hits$transect)) 

hits$hits_unique <- do.call(paste, c(hits[c("transect", "point_number")], sep = " ")) #create a new column in the hits data with transect and hit combined to make unique combination within plot, this is to identify unique samples for the calculation of cover and species accumulation curves etc.

hits$site_unique <- do.call(paste, c(hits[c("site_location_name", "site_location_visit_id")], sep = "-")) #because there are multiple visits for some - and potentially all - sites, we have queried unique visit_id numbers from the database in the raw PI data. Here we are making a new single field combining site and visit ids to get unique plot/visit identifiers that still have the plot site name in it because a straight visit number would be harder to interpret and use for labels etc...

#count combined (PI) cover scores for each species in each plot:
total.points.fun <- function(x) {return(length(unique(hits[which(hits$site_unique == x),]$hits_unique)))} #function to go through a list of plot names and count how many unique hits there were (for a standard plot, this will equal 1010)
total.points <- data.frame(site_unique = unique(hits$site_unique), total.points = unlist(lapply(unique(hits$site_unique), total.points.fun))) #site/visit and associated number of unique PI hits taken
covers <- count(hits[which(as.character(hits$in_canopy_sky) == "FALSE"),], c("site_unique", "herbarium_determination")) #counts number of rows with same site and species name, last colname 'freq', i.e. counting the number of hits for a given species in a given plot. In canopy sky hits are removed (==TRUE) first so that projected foliage cover rather than opaque canopy cover is calculated. IF YOU WANT opaque canopy cover, would need remove that part - ***It would be neater to contain that choice within a function where this is an argument, such as cover.type=c("PFC", "opaque")...
covers <- merge(covers, total.points, by="site_unique") #merge to get the hit counts for species in df with total hits for each plot
covers$percent <- covers$freq/covers$total.points*100 #add a new column to convert from number of hits to percent. Some plots have less or more than the standard 1010 PI hits for various reasons, so this ensures dividing by the actual number of unique hits, which is calculated form the raw data and unique transect/number combos
covers <- na.omit(covers) #to remove percents for records with no herbarium determination


#####
#generate a sites by species matrix with these percents as the values:
cover_matrix <- mama(covers[,-c(3, 4)]) #third/fourth columns (count of individual hits and total hits) excluded as we want to the mama function to read our fourth column 'percent' [percent cover] as the abundance value (assumed to be the 3rd column): this generates a data.frame with sites as rows and species as columns, with percent covers from PI hits as values

write.csv(cover_matrix, file="sitesVspecies_percent_cover_PI.txt") #write to file the abundance/occurrence matrix

