#Following 'compile_ausplots_vegPI.R', this script generates a species~sites occurrence matrix with the frequency of species within the 10 point intercept transects within each plot as values, and writes it to file. 
#
#Authors:
#Greg Guerin

library(simba)
library(plyr)

#object 'hits' is generated by 'compile_ausplots_vegPI.R' and is the compiled but raw point intercept hit data from all plots

################################

transects <- count(hits, c("site_location_name", "herbarium_determination", "transect")) #count PI records for each uniqe plot/species/transect combo
transects$freq <- 1 #revert to 1 (presence)
freqs <- count(transects, c("site_location_name", "herbarium_determination")) #count transect presences per species per plot, e.g. 5 means that species was recorded on 5 of the trasects

freqs$freq <- freqs$freq/10 #divide by ten to convert to actual frequency (should range from 0.1 to 1)

freq_matrix <- mama(freqs) #a species ~ sites matrix with the frequencies as values, and zeros if species occur on no transect for a plot

write.csv(freq_matrix, file="sitesVspecies_freq_transects.txt") #write to file


