#Following 'compile_ausplots_vegPI.R', this script generates a species~sites occurrence matrix with the frequency of species within the 10 point intercept transects within each plot as values, and writes it to file. 
#
#Authors:
#Greg Guerin

#setwd()

library(simba)

#object 'hits' is generated by 'compile_ausplots_vegPI.R' and is the compiled but rawa point intercept hit data from all plots

#tidy up redundant transect labels:
hits$standard <- hits$transect #copy the vector which says which PI transect the hit was on so we can have the original one as well as the altered one
delete <- grep("E1", hits$transect) #list of positions in the vector in which the text containts E1
hits$standard[delete] <- "E1-W1" # subsets the labels to those containing E1 and changes them to the same label

delete <- grep("E2", hits$transect)
hits$standard[delete] <- "E2-W2" 

delete <- grep("E3", hits$transect)
hits$standard[delete] <- "E3-W3"

delete <- grep("E4", hits$transect)
hits$standard[delete] <- "E4-W4"

delete <- grep("E5", hits$transect)
hits$standard[delete] <- "E5-W5"

delete <- grep("N1", hits$transect)
hits$standard[delete] <- "N1-S1"

delete <- grep("N2", hits$transect)
hits$standard[delete] <- "N2-S2" 

delete <- grep("N3", hits$transect)
hits$standard[delete] <- "N3-S3"

delete <- grep("N4", hits$transect)
hits$standard[delete] <- "N4-S4"

delete <- grep("N5", hits$transect)
hits$standard[delete] <- "N5-S5"
   

hits$standard <- as.factor(as.character(hits$standard)) #reset levels

#levels(hits$standard) 

transects <- count(hits, c("site_location_name", "herbarium_determination", "standard")) #count PI records for each uniqe plot/species/transect combo
transects$freq <- 1 #revert to 1 (presence)
freqs <- count(transects, c("site_location_name", "herbarium_determination")) #count transect presences per species per plot

freqs$freq <- freqs$freq/10 #divide by ten to convert to actual frequency (should range from 0.1 to 1)

freq_matrix <- mama(freqs) #a species ~ sites matrix with the frequencies as values, and zeros if species occur on no transect for a plot

write.csv(freq_matrix, file="sitesVspecies_freq_transects.txt") #write to file


