#This script compiles files for individual AusPlots with vegetation point intercept hit data into a siungle object/file and subsequently generates a species~sites occurrence matrix with percent cover scores as values. 
#
#Authors:
#Greg Guerin

setwd()

file_list <- Sys.glob("~/extractedData/veg/vegPI*.csv") #call a list of files with same prefix, where 'extractedData' folder was generated by 'read_ausplots_data.R'


trim.trailing <- function (x) sub("\\s+$", "", x) #function that strips trailing white spaces from entries in d.f.

#function to open files from a list, and append the data to a single output file
extract_hits <- function(file_list) {
	working_file <- read.csv(file=file_list[1], sep=",", header=TRUE)	
	document <- as.data.frame(matrix(nrow=1, ncol=ncol(working_file))) 
	colnames(document) <- colnames(working_file)
	for (i in 1:length(file_list)) {
	working_file <- try(read.csv(file=file_list[i], sep=",", header=TRUE))
	if(class(working_file)=="try-error") {
		working_file <- NULL
	}
	if(class(working_file)=="data.frame") {
		document <- rbind(document, working_file)
	}
	
	message("Dataset added")
	message(i)
	}
document <- document[-1,]
write.csv(document, file="PI_compiled.txt")
}

extract_hits(file_list) #generates a file with PI hits as rows, identified by site name, species and transect number

hits <- read.table(file="PI_compiled.txt", sep=",", header=TRUE) #read file back into R

#...  needs further clearing up as follows
hits$herbarium_determination <- trim.trailing(hits$herbarium_determination) #clear white spaces that stuff up recognising same spp so you get unrecognised duplicates
library(R.utils)
hits$herbarium_determination <- tolower(hits$herbarium_determination)
hits$herbarium_determination <- capitalize(hits$herbarium_determination)



#couint combined (PI) cover scores for each species in each plot:
library(plyr)
covers <- count(hits, c("site_location_name", "herbarium_determination")) #counts number of rows with same site and species name, last colname 'freq'
covers$percent <- covers$freq/1010*100 #add a new column to this with conversion from number of hits to percent ##NB 1010 is the total number of PI points in an ausplot: 10 * 101, then *100 for percent. So we now how a df with site, species, hits and percent cover

#generate a sites by species matrix with these percents as the values:
library(simba)
cover_matrix <- mama(covers[,-3]) #third column (count of individual hits) excluded as we want to the mama function to read our fourth column 'percent' [percent cover] as the abundance value (assumed to be the 3rd column): this generates a data.frame with sites as rows and species as columns, with percent covers from PI hits as values

write.csv(cover_matrix, file="sitesVspecies_percent_cover_PI.txt") #write to file the occurrence matrix

